name: CI

on: [push, pull_request]

jobs:
  build-centos7-jemalloc:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        apt-get update
        apt-get install -y gnupg2 
        echo "deb http://dk.archive.ubuntu.com/ubuntu/ xenial main" >> /etc/apt/sources.list
        echo "deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe" >> /etc/apt/sources.list
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
        apt-get update
        apt-get install -y make gcc-4.9
        make CC=gcc-4.9 REDIS_CFLAGS='-Werror'

